name: Node.js CI and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ec2-key.pem ubuntu@13.60.119.208 << 'EOF'
          cd /var/www/html/martial_arts_hub || exit
          git pull origin main
          npm install
          npm run build
        EOF
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
