name: Node.js CI and Deploy

on:
  push:
    branches: [ "feat/ci-cd" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    # Deploy to EC2 via SSH
    - name: Deploy to EC2
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-client
        echo "${{ secrets.EC2_SSH_KEY }}" > ec2-key.pem
        chmod 600 ec2-key.pem

        # Replace with your EC2 instance's user, IP, and path
        ssh -o StrictHostKeyChecking=no -i ec2-key.pem ubuntu@13.60.119.208 'cd /var/www/html/martial_arts_hub && git pull origin main && npm install'
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
